/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using Knedlex.Roblox.Avatar.ApiV1.Model;

namespace Knedlex.Roblox.Avatar.ApiV1.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRecentItemApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Returns a list of recent items  Recent items can be Assets or Outfits
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Avatar.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentItemListType"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel</returns>
        RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel V1RecentItemsRecentItemListTypeListGet(int recentItemListType, int operationIndex = 0);

        /// <summary>
        /// Returns a list of recent items  Recent items can be Assets or Outfits
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Avatar.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentItemListType"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel</returns>
        ApiResponse<RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel> V1RecentItemsRecentItemListTypeListGetWithHttpInfo(int recentItemListType, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRecentItemApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Returns a list of recent items  Recent items can be Assets or Outfits
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Avatar.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentItemListType"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel</returns>
        System.Threading.Tasks.Task<RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel> V1RecentItemsRecentItemListTypeListGetAsync(int recentItemListType, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Returns a list of recent items  Recent items can be Assets or Outfits
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Avatar.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentItemListType"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel>> V1RecentItemsRecentItemListTypeListGetWithHttpInfoAsync(int recentItemListType, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRecentItemApi : IRecentItemApiSync, IRecentItemApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RecentItemApi : IRecentItemApi
    {
        private Knedlex.Roblox.Avatar.ApiV1.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RecentItemApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RecentItemApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecentItemApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RecentItemApi(string basePath)
        {
            this.Configuration = Knedlex.Roblox.Avatar.ApiV1.Client.Configuration.MergeConfigurations(
                Knedlex.Roblox.Avatar.ApiV1.Client.GlobalConfiguration.Instance,
                new Knedlex.Roblox.Avatar.ApiV1.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Knedlex.Roblox.Avatar.ApiV1.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Knedlex.Roblox.Avatar.ApiV1.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Knedlex.Roblox.Avatar.ApiV1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecentItemApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RecentItemApi(Knedlex.Roblox.Avatar.ApiV1.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Knedlex.Roblox.Avatar.ApiV1.Client.Configuration.MergeConfigurations(
                Knedlex.Roblox.Avatar.ApiV1.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Knedlex.Roblox.Avatar.ApiV1.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Knedlex.Roblox.Avatar.ApiV1.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Knedlex.Roblox.Avatar.ApiV1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecentItemApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RecentItemApi(Knedlex.Roblox.Avatar.ApiV1.Client.ISynchronousClient client, Knedlex.Roblox.Avatar.ApiV1.Client.IAsynchronousClient asyncClient, Knedlex.Roblox.Avatar.ApiV1.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Knedlex.Roblox.Avatar.ApiV1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Knedlex.Roblox.Avatar.ApiV1.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Knedlex.Roblox.Avatar.ApiV1.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Knedlex.Roblox.Avatar.ApiV1.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Knedlex.Roblox.Avatar.ApiV1.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Returns a list of recent items  Recent items can be Assets or Outfits 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Avatar.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentItemListType"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel</returns>
        public RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel V1RecentItemsRecentItemListTypeListGet(int recentItemListType, int operationIndex = 0)
        {
            Knedlex.Roblox.Avatar.ApiV1.Client.ApiResponse<RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel> localVarResponse = V1RecentItemsRecentItemListTypeListGetWithHttpInfo(recentItemListType);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Returns a list of recent items  Recent items can be Assets or Outfits 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Avatar.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentItemListType"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel</returns>
        public Knedlex.Roblox.Avatar.ApiV1.Client.ApiResponse<RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel> V1RecentItemsRecentItemListTypeListGetWithHttpInfo(int recentItemListType, int operationIndex = 0)
        {
            Knedlex.Roblox.Avatar.ApiV1.Client.RequestOptions localVarRequestOptions = new Knedlex.Roblox.Avatar.ApiV1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "text/json"
            };

            var localVarContentType = Knedlex.Roblox.Avatar.ApiV1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Knedlex.Roblox.Avatar.ApiV1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("recentItemListType", Knedlex.Roblox.Avatar.ApiV1.Client.ClientUtils.ParameterToString(recentItemListType)); // path parameter

            localVarRequestOptions.Operation = "RecentItemApi.V1RecentItemsRecentItemListTypeListGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel>("/v1/recent-items/{recentItemListType}/list", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("V1RecentItemsRecentItemListTypeListGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Returns a list of recent items  Recent items can be Assets or Outfits 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Avatar.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentItemListType"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel</returns>
        public async System.Threading.Tasks.Task<RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel> V1RecentItemsRecentItemListTypeListGetAsync(int recentItemListType, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Knedlex.Roblox.Avatar.ApiV1.Client.ApiResponse<RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel> localVarResponse = await V1RecentItemsRecentItemListTypeListGetWithHttpInfoAsync(recentItemListType, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Returns a list of recent items  Recent items can be Assets or Outfits 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Avatar.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentItemListType"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel)</returns>
        public async System.Threading.Tasks.Task<Knedlex.Roblox.Avatar.ApiV1.Client.ApiResponse<RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel>> V1RecentItemsRecentItemListTypeListGetWithHttpInfoAsync(int recentItemListType, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Knedlex.Roblox.Avatar.ApiV1.Client.RequestOptions localVarRequestOptions = new Knedlex.Roblox.Avatar.ApiV1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "text/json"
            };

            var localVarContentType = Knedlex.Roblox.Avatar.ApiV1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Knedlex.Roblox.Avatar.ApiV1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("recentItemListType", Knedlex.Roblox.Avatar.ApiV1.Client.ClientUtils.ParameterToString(recentItemListType)); // path parameter

            localVarRequestOptions.Operation = "RecentItemApi.V1RecentItemsRecentItemListTypeListGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel>("/v1/recent-items/{recentItemListType}/list", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("V1RecentItemsRecentItemListTypeListGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
