/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Knedlex.Roblox.Avatar.ApiV1.Client;
using Knedlex.Roblox.Avatar.ApiV1.Api;
// uncomment below to import models
//using Knedlex.Roblox.Avatar.ApiV1.Model;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Api
{
    /// <summary>
    ///  Class for testing AvatarApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AvatarApiTests : IDisposable
    {
        private AvatarApi instance;

        public AvatarApiTests()
        {
            instance = new AvatarApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvatarApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AvatarApi
            //Assert.IsType<AvatarApi>(instance);
        }

        /// <summary>
        /// Test V1AvatarAssetsAssetIdRemovePost
        /// </summary>
        [Fact]
        public void V1AvatarAssetsAssetIdRemovePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long assetId = null;
            //var response = instance.V1AvatarAssetsAssetIdRemovePost(assetId);
            //Assert.IsType<RobloxApiAvatarModelsAvatarApiSuccessResponse>(response);
        }

        /// <summary>
        /// Test V1AvatarAssetsAssetIdWearPost
        /// </summary>
        [Fact]
        public void V1AvatarAssetsAssetIdWearPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long assetId = null;
            //var response = instance.V1AvatarAssetsAssetIdWearPost(assetId);
            //Assert.IsType<RobloxApiAvatarModelsAvatarApiSuccessResponse>(response);
        }

        /// <summary>
        /// Test V1AvatarGet
        /// </summary>
        [Fact]
        public void V1AvatarGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1AvatarGet();
            //Assert.IsType<RobloxApiAvatarModelsAvatarModelV2>(response);
        }

        /// <summary>
        /// Test V1AvatarMetadataGet
        /// </summary>
        [Fact]
        public void V1AvatarMetadataGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1AvatarMetadataGet();
            //Assert.IsType<RobloxApiAvatarModelsAvatarMetadataModel>(response);
        }

        /// <summary>
        /// Test V1AvatarRedrawThumbnailPost
        /// </summary>
        [Fact]
        public void V1AvatarRedrawThumbnailPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1AvatarRedrawThumbnailPost();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test V1AvatarRulesGet
        /// </summary>
        [Fact]
        public void V1AvatarRulesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1AvatarRulesGet();
            //Assert.IsType<RobloxApiAvatarModelsAvatarRulesModel>(response);
        }

        /// <summary>
        /// Test V1AvatarSetBodyColorsPost
        /// </summary>
        [Fact]
        public void V1AvatarSetBodyColorsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RobloxApiAvatarModelsBodyColorsModel bodyColorsModel = null;
            //var response = instance.V1AvatarSetBodyColorsPost(bodyColorsModel);
            //Assert.IsType<RobloxApiAvatarModelsAvatarApiSuccessResponse>(response);
        }

        /// <summary>
        /// Test V1AvatarSetPlayerAvatarTypePost
        /// </summary>
        [Fact]
        public void V1AvatarSetPlayerAvatarTypePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RobloxApiAvatarModelsPlayerAvatarTypeModel playerAvatarTypeModel = null;
            //var response = instance.V1AvatarSetPlayerAvatarTypePost(playerAvatarTypeModel);
            //Assert.IsType<RobloxApiAvatarModelsAvatarApiSuccessResponse>(response);
        }

        /// <summary>
        /// Test V1AvatarSetScalesPost
        /// </summary>
        [Fact]
        public void V1AvatarSetScalesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RobloxWebResponsesAvatarScaleModel scalesModel = null;
            //var response = instance.V1AvatarSetScalesPost(scalesModel);
            //Assert.IsType<RobloxApiAvatarModelsAvatarApiSuccessResponse>(response);
        }

        /// <summary>
        /// Test V1AvatarSetWearingAssetsPost
        /// </summary>
        [Fact]
        public void V1AvatarSetWearingAssetsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RobloxApiAvatarModelsAssetIdListModel assetIdsModel = null;
            //var response = instance.V1AvatarSetWearingAssetsPost(assetIdsModel);
            //Assert.IsType<RobloxApiAvatarModelsWearResponseModel>(response);
        }

        /// <summary>
        /// Test V1GameStartInfoGet
        /// </summary>
        [Fact]
        public void V1GameStartInfoGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long universeId = null;
            //var response = instance.V1GameStartInfoGet(universeId);
            //Assert.IsType<RobloxApiAvatarModelsGameStartInfoResponse>(response);
        }

        /// <summary>
        /// Test V1UsersUserIdAvatarGet
        /// </summary>
        [Fact]
        public void V1UsersUserIdAvatarGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long userId = null;
            //var response = instance.V1UsersUserIdAvatarGet(userId);
            //Assert.IsType<RobloxApiAvatarModelsAvatarModelV2>(response);
        }

        /// <summary>
        /// Test V1UsersUserIdCurrentlyWearingGet
        /// </summary>
        [Fact]
        public void V1UsersUserIdCurrentlyWearingGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long userId = null;
            //var response = instance.V1UsersUserIdCurrentlyWearingGet(userId);
            //Assert.IsType<RobloxApiAvatarModelsAssetIdListModel>(response);
        }

        /// <summary>
        /// Test V1UsersUserIdOutfitsGet
        /// </summary>
        [Fact]
        public void V1UsersUserIdOutfitsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long userId = null;
            //string outfitType = null;
            //int? page = null;
            //int? itemsPerPage = null;
            //bool? isEditable = null;
            //var response = instance.V1UsersUserIdOutfitsGet(userId, outfitType, page, itemsPerPage, isEditable);
            //Assert.IsType<RobloxApiAvatarModelsAvatarFilteredPageResponseRobloxApiAvatarModelsOutfitModel>(response);
        }
    }
}
