/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Knedlex.Roblox.Avatar.ApiV1.Client;
using Knedlex.Roblox.Avatar.ApiV1.Api;
// uncomment below to import models
//using Knedlex.Roblox.Avatar.ApiV1.Model;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Api
{
    /// <summary>
    ///  Class for testing OutfitsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OutfitsApiTests : IDisposable
    {
        private OutfitsApi instance;

        public OutfitsApiTests()
        {
            instance = new OutfitsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutfitsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OutfitsApi
            //Assert.IsType<OutfitsApi>(instance);
        }

        /// <summary>
        /// Test V1OutfitsCreatePost
        /// </summary>
        [Fact]
        public void V1OutfitsCreatePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RobloxApiAvatarModelsOutfitUpdateModelV1 outfitUpdateModel = null;
            //var response = instance.V1OutfitsCreatePost(outfitUpdateModel);
            //Assert.IsType<RobloxApiAvatarModelsAvatarApiSuccessResponse>(response);
        }

        /// <summary>
        /// Test V1OutfitsUserOutfitIdDeletePost
        /// </summary>
        [Fact]
        public void V1OutfitsUserOutfitIdDeletePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long userOutfitId = null;
            //var response = instance.V1OutfitsUserOutfitIdDeletePost(userOutfitId);
            //Assert.IsType<RobloxApiAvatarModelsAvatarApiSuccessResponse>(response);
        }

        /// <summary>
        /// Test V1OutfitsUserOutfitIdDetailsGet
        /// </summary>
        [Fact]
        public void V1OutfitsUserOutfitIdDetailsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long userOutfitId = null;
            //var response = instance.V1OutfitsUserOutfitIdDetailsGet(userOutfitId);
            //Assert.IsType<RobloxApiAvatarModelsOutfitDetailsModel>(response);
        }

        /// <summary>
        /// Test V1OutfitsUserOutfitIdPatch
        /// </summary>
        [Fact]
        public void V1OutfitsUserOutfitIdPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long userOutfitId = null;
            //RobloxApiAvatarModelsOutfitUpdateModelV1 outfitUpdateModel = null;
            //var response = instance.V1OutfitsUserOutfitIdPatch(userOutfitId, outfitUpdateModel);
            //Assert.IsType<RobloxApiAvatarModelsOutfitModel>(response);
        }

        /// <summary>
        /// Test V1OutfitsUserOutfitIdUpdatePost
        /// </summary>
        [Fact]
        public void V1OutfitsUserOutfitIdUpdatePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long userOutfitId = null;
            //RobloxApiAvatarModelsOutfitUpdateModelV1 outfitUpdateModel = null;
            //var response = instance.V1OutfitsUserOutfitIdUpdatePost(userOutfitId, outfitUpdateModel);
            //Assert.IsType<RobloxApiAvatarModelsAvatarApiSuccessResponse>(response);
        }

        /// <summary>
        /// Test V1OutfitsUserOutfitIdWearPost
        /// </summary>
        [Fact]
        public void V1OutfitsUserOutfitIdWearPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long userOutfitId = null;
            //var response = instance.V1OutfitsUserOutfitIdWearPost(userOutfitId);
            //Assert.IsType<RobloxApiAvatarModelsWearResponseModel>(response);
        }
    }
}
