/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Knedlex.Roblox.Avatar.ApiV1.Client;
using Knedlex.Roblox.Avatar.ApiV1.Api;
// uncomment below to import models
//using Knedlex.Roblox.Avatar.ApiV1.Model;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Api
{
    /// <summary>
    ///  Class for testing RecentItemApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RecentItemApiTests : IDisposable
    {
        private RecentItemApi instance;

        public RecentItemApiTests()
        {
            instance = new RecentItemApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecentItemApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RecentItemApi
            //Assert.IsType<RecentItemApi>(instance);
        }

        /// <summary>
        /// Test V1RecentItemsRecentItemListTypeListGet
        /// </summary>
        [Fact]
        public void V1RecentItemsRecentItemListTypeListGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int recentItemListType = null;
            //var response = instance.V1RecentItemsRecentItemListTypeListGet(recentItemListType);
            //Assert.IsType<RobloxWebWebAPIModelsApiLegacyPageResponseRobloxApiAvatarModelsRecentItemModel>(response);
        }
    }
}
