/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing AvatarCommonModelsAccessoryRefinementModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvatarCommonModelsAccessoryRefinementModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AvatarCommonModelsAccessoryRefinementModel
        //private AvatarCommonModelsAccessoryRefinementModel instance;

        public AvatarCommonModelsAccessoryRefinementModelTests()
        {
            // TODO uncomment below to create an instance of AvatarCommonModelsAccessoryRefinementModel
            //instance = new AvatarCommonModelsAccessoryRefinementModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvatarCommonModelsAccessoryRefinementModel
        /// </summary>
        [Fact]
        public void AvatarCommonModelsAccessoryRefinementModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" AvatarCommonModelsAccessoryRefinementModel
            //Assert.IsType<AvatarCommonModelsAccessoryRefinementModel>(instance);
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

        /// <summary>
        /// Test the property 'Rotation'
        /// </summary>
        [Fact]
        public void RotationTest()
        {
            // TODO unit test for the property 'Rotation'
        }

        /// <summary>
        /// Test the property 'Scale'
        /// </summary>
        [Fact]
        public void ScaleTest()
        {
            // TODO unit test for the property 'Scale'
        }
    }
}
