/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing AvatarCommonModelsAccessoryPositionModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvatarCommonModelsAccessoryPositionModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AvatarCommonModelsAccessoryPositionModel
        //private AvatarCommonModelsAccessoryPositionModel instance;

        public AvatarCommonModelsAccessoryPositionModelTests()
        {
            // TODO uncomment below to create an instance of AvatarCommonModelsAccessoryPositionModel
            //instance = new AvatarCommonModelsAccessoryPositionModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvatarCommonModelsAccessoryPositionModel
        /// </summary>
        [Fact]
        public void AvatarCommonModelsAccessoryPositionModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" AvatarCommonModelsAccessoryPositionModel
            //Assert.IsType<AvatarCommonModelsAccessoryPositionModel>(instance);
        }

        /// <summary>
        /// Test the property 'XPosition'
        /// </summary>
        [Fact]
        public void XPositionTest()
        {
            // TODO unit test for the property 'XPosition'
        }

        /// <summary>
        /// Test the property 'YPosition'
        /// </summary>
        [Fact]
        public void YPositionTest()
        {
            // TODO unit test for the property 'YPosition'
        }

        /// <summary>
        /// Test the property 'ZPosition'
        /// </summary>
        [Fact]
        public void ZPositionTest()
        {
            // TODO unit test for the property 'ZPosition'
        }
    }
}
