/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing AvatarCommonModelsAccessoryScaleModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvatarCommonModelsAccessoryScaleModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AvatarCommonModelsAccessoryScaleModel
        //private AvatarCommonModelsAccessoryScaleModel instance;

        public AvatarCommonModelsAccessoryScaleModelTests()
        {
            // TODO uncomment below to create an instance of AvatarCommonModelsAccessoryScaleModel
            //instance = new AvatarCommonModelsAccessoryScaleModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvatarCommonModelsAccessoryScaleModel
        /// </summary>
        [Fact]
        public void AvatarCommonModelsAccessoryScaleModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" AvatarCommonModelsAccessoryScaleModel
            //Assert.IsType<AvatarCommonModelsAccessoryScaleModel>(instance);
        }

        /// <summary>
        /// Test the property 'XScale'
        /// </summary>
        [Fact]
        public void XScaleTest()
        {
            // TODO unit test for the property 'XScale'
        }

        /// <summary>
        /// Test the property 'YScale'
        /// </summary>
        [Fact]
        public void YScaleTest()
        {
            // TODO unit test for the property 'YScale'
        }

        /// <summary>
        /// Test the property 'ZScale'
        /// </summary>
        [Fact]
        public void ZScaleTest()
        {
            // TODO unit test for the property 'ZScale'
        }
    }
}
