/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing AvatarCommonModelsAccessoryRotationModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvatarCommonModelsAccessoryRotationModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AvatarCommonModelsAccessoryRotationModel
        //private AvatarCommonModelsAccessoryRotationModel instance;

        public AvatarCommonModelsAccessoryRotationModelTests()
        {
            // TODO uncomment below to create an instance of AvatarCommonModelsAccessoryRotationModel
            //instance = new AvatarCommonModelsAccessoryRotationModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvatarCommonModelsAccessoryRotationModel
        /// </summary>
        [Fact]
        public void AvatarCommonModelsAccessoryRotationModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" AvatarCommonModelsAccessoryRotationModel
            //Assert.IsType<AvatarCommonModelsAccessoryRotationModel>(instance);
        }

        /// <summary>
        /// Test the property 'XRotation'
        /// </summary>
        [Fact]
        public void XRotationTest()
        {
            // TODO unit test for the property 'XRotation'
        }

        /// <summary>
        /// Test the property 'YRotation'
        /// </summary>
        [Fact]
        public void YRotationTest()
        {
            // TODO unit test for the property 'YRotation'
        }

        /// <summary>
        /// Test the property 'ZRotation'
        /// </summary>
        [Fact]
        public void ZRotationTest()
        {
            // TODO unit test for the property 'ZRotation'
        }
    }
}
