/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxAvatarcoreSharedV3Beta1AssetPosition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxAvatarcoreSharedV3Beta1AssetPositionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxAvatarcoreSharedV3Beta1AssetPosition
        //private RobloxAvatarcoreSharedV3Beta1AssetPosition instance;

        public RobloxAvatarcoreSharedV3Beta1AssetPositionTests()
        {
            // TODO uncomment below to create an instance of RobloxAvatarcoreSharedV3Beta1AssetPosition
            //instance = new RobloxAvatarcoreSharedV3Beta1AssetPosition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxAvatarcoreSharedV3Beta1AssetPosition
        /// </summary>
        [Fact]
        public void RobloxAvatarcoreSharedV3Beta1AssetPositionInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxAvatarcoreSharedV3Beta1AssetPosition
            //Assert.IsType<RobloxAvatarcoreSharedV3Beta1AssetPosition>(instance);
        }

        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Fact]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }

        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Fact]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }

        /// <summary>
        /// Test the property 'Z'
        /// </summary>
        [Fact]
        public void ZTest()
        {
            // TODO unit test for the property 'Z'
        }
    }
}
