/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel
        //private RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel instance;

        public RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModelTests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel
            //instance = new RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel
            //Assert.IsType<RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel>(instance);
        }

        /// <summary>
        /// Test the property 'AssetID'
        /// </summary>
        [Fact]
        public void AssetIDTest()
        {
            // TODO unit test for the property 'AssetID'
        }

        /// <summary>
        /// Test the property 'AssetTypeID'
        /// </summary>
        [Fact]
        public void AssetTypeIDTest()
        {
            // TODO unit test for the property 'AssetTypeID'
        }

        /// <summary>
        /// Test the property 'IsPlayerChoice'
        /// </summary>
        [Fact]
        public void IsPlayerChoiceTest()
        {
            // TODO unit test for the property 'IsPlayerChoice'
        }
    }
}
