/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsRecentItemModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsRecentItemModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsRecentItemModel
        //private RobloxApiAvatarModelsRecentItemModel instance;

        public RobloxApiAvatarModelsRecentItemModelTests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsRecentItemModel
            //instance = new RobloxApiAvatarModelsRecentItemModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsRecentItemModel
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsRecentItemModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsRecentItemModel
            //Assert.IsType<RobloxApiAvatarModelsRecentItemModel>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'AssetType'
        /// </summary>
        [Fact]
        public void AssetTypeTest()
        {
            // TODO unit test for the property 'AssetType'
        }

        /// <summary>
        /// Test the property 'IsEditable'
        /// </summary>
        [Fact]
        public void IsEditableTest()
        {
            // TODO unit test for the property 'IsEditable'
        }
    }
}
