/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsScaleRulesModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsScaleRulesModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsScaleRulesModel
        //private RobloxApiAvatarModelsScaleRulesModel instance;

        public RobloxApiAvatarModelsScaleRulesModelTests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsScaleRulesModel
            //instance = new RobloxApiAvatarModelsScaleRulesModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsScaleRulesModel
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsScaleRulesModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsScaleRulesModel
            //Assert.IsType<RobloxApiAvatarModelsScaleRulesModel>(instance);
        }

        /// <summary>
        /// Test the property 'Min'
        /// </summary>
        [Fact]
        public void MinTest()
        {
            // TODO unit test for the property 'Min'
        }

        /// <summary>
        /// Test the property 'Max'
        /// </summary>
        [Fact]
        public void MaxTest()
        {
            // TODO unit test for the property 'Max'
        }

        /// <summary>
        /// Test the property 'Increment'
        /// </summary>
        [Fact]
        public void IncrementTest()
        {
            // TODO unit test for the property 'Increment'
        }
    }
}
