/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsWearResponseModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsWearResponseModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsWearResponseModel
        //private RobloxApiAvatarModelsWearResponseModel instance;

        public RobloxApiAvatarModelsWearResponseModelTests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsWearResponseModel
            //instance = new RobloxApiAvatarModelsWearResponseModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsWearResponseModel
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsWearResponseModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsWearResponseModel
            //Assert.IsType<RobloxApiAvatarModelsWearResponseModel>(instance);
        }

        /// <summary>
        /// Test the property 'InvalidAssets'
        /// </summary>
        [Fact]
        public void InvalidAssetsTest()
        {
            // TODO unit test for the property 'InvalidAssets'
        }

        /// <summary>
        /// Test the property 'InvalidAssetIds'
        /// </summary>
        [Fact]
        public void InvalidAssetIdsTest()
        {
            // TODO unit test for the property 'InvalidAssetIds'
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
    }
}
