/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsAvatarRulesModelAccessoryRefinementLowerBounds
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsAvatarRulesModelAccessoryRefinementLowerBoundsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsAvatarRulesModelAccessoryRefinementLowerBounds
        //private RobloxApiAvatarModelsAvatarRulesModelAccessoryRefinementLowerBounds instance;

        public RobloxApiAvatarModelsAvatarRulesModelAccessoryRefinementLowerBoundsTests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsAvatarRulesModelAccessoryRefinementLowerBounds
            //instance = new RobloxApiAvatarModelsAvatarRulesModelAccessoryRefinementLowerBounds();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsAvatarRulesModelAccessoryRefinementLowerBounds
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsAvatarRulesModelAccessoryRefinementLowerBoundsInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsAvatarRulesModelAccessoryRefinementLowerBounds
            //Assert.IsType<RobloxApiAvatarModelsAvatarRulesModelAccessoryRefinementLowerBounds>(instance);
        }

        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }

        /// <summary>
        /// Test the property 'TShirt'
        /// </summary>
        [Fact]
        public void TShirtTest()
        {
            // TODO unit test for the property 'TShirt'
        }

        /// <summary>
        /// Test the property 'Audio'
        /// </summary>
        [Fact]
        public void AudioTest()
        {
            // TODO unit test for the property 'Audio'
        }

        /// <summary>
        /// Test the property 'Mesh'
        /// </summary>
        [Fact]
        public void MeshTest()
        {
            // TODO unit test for the property 'Mesh'
        }

        /// <summary>
        /// Test the property 'Lua'
        /// </summary>
        [Fact]
        public void LuaTest()
        {
            // TODO unit test for the property 'Lua'
        }

        /// <summary>
        /// Test the property 'HTML'
        /// </summary>
        [Fact]
        public void HTMLTest()
        {
            // TODO unit test for the property 'HTML'
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'Hat'
        /// </summary>
        [Fact]
        public void HatTest()
        {
            // TODO unit test for the property 'Hat'
        }

        /// <summary>
        /// Test the property 'Place'
        /// </summary>
        [Fact]
        public void PlaceTest()
        {
            // TODO unit test for the property 'Place'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

        /// <summary>
        /// Test the property 'Shirt'
        /// </summary>
        [Fact]
        public void ShirtTest()
        {
            // TODO unit test for the property 'Shirt'
        }

        /// <summary>
        /// Test the property 'Pants'
        /// </summary>
        [Fact]
        public void PantsTest()
        {
            // TODO unit test for the property 'Pants'
        }

        /// <summary>
        /// Test the property 'Decal'
        /// </summary>
        [Fact]
        public void DecalTest()
        {
            // TODO unit test for the property 'Decal'
        }

        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Fact]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }

        /// <summary>
        /// Test the property 'Head'
        /// </summary>
        [Fact]
        public void HeadTest()
        {
            // TODO unit test for the property 'Head'
        }

        /// <summary>
        /// Test the property 'Face'
        /// </summary>
        [Fact]
        public void FaceTest()
        {
            // TODO unit test for the property 'Face'
        }

        /// <summary>
        /// Test the property 'Gear'
        /// </summary>
        [Fact]
        public void GearTest()
        {
            // TODO unit test for the property 'Gear'
        }

        /// <summary>
        /// Test the property 'Badge'
        /// </summary>
        [Fact]
        public void BadgeTest()
        {
            // TODO unit test for the property 'Badge'
        }

        /// <summary>
        /// Test the property 'GroupEmblem'
        /// </summary>
        [Fact]
        public void GroupEmblemTest()
        {
            // TODO unit test for the property 'GroupEmblem'
        }

        /// <summary>
        /// Test the property 'Animation'
        /// </summary>
        [Fact]
        public void AnimationTest()
        {
            // TODO unit test for the property 'Animation'
        }

        /// <summary>
        /// Test the property 'Arms'
        /// </summary>
        [Fact]
        public void ArmsTest()
        {
            // TODO unit test for the property 'Arms'
        }

        /// <summary>
        /// Test the property 'Legs'
        /// </summary>
        [Fact]
        public void LegsTest()
        {
            // TODO unit test for the property 'Legs'
        }

        /// <summary>
        /// Test the property 'Torso'
        /// </summary>
        [Fact]
        public void TorsoTest()
        {
            // TODO unit test for the property 'Torso'
        }

        /// <summary>
        /// Test the property 'RightArm'
        /// </summary>
        [Fact]
        public void RightArmTest()
        {
            // TODO unit test for the property 'RightArm'
        }

        /// <summary>
        /// Test the property 'LeftArm'
        /// </summary>
        [Fact]
        public void LeftArmTest()
        {
            // TODO unit test for the property 'LeftArm'
        }

        /// <summary>
        /// Test the property 'LeftLeg'
        /// </summary>
        [Fact]
        public void LeftLegTest()
        {
            // TODO unit test for the property 'LeftLeg'
        }

        /// <summary>
        /// Test the property 'RightLeg'
        /// </summary>
        [Fact]
        public void RightLegTest()
        {
            // TODO unit test for the property 'RightLeg'
        }

        /// <summary>
        /// Test the property 'Package'
        /// </summary>
        [Fact]
        public void PackageTest()
        {
            // TODO unit test for the property 'Package'
        }

        /// <summary>
        /// Test the property 'YouTubeVideo'
        /// </summary>
        [Fact]
        public void YouTubeVideoTest()
        {
            // TODO unit test for the property 'YouTubeVideo'
        }

        /// <summary>
        /// Test the property 'GamePass'
        /// </summary>
        [Fact]
        public void GamePassTest()
        {
            // TODO unit test for the property 'GamePass'
        }

        /// <summary>
        /// Test the property 'App'
        /// </summary>
        [Fact]
        public void AppTest()
        {
            // TODO unit test for the property 'App'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Plugin'
        /// </summary>
        [Fact]
        public void PluginTest()
        {
            // TODO unit test for the property 'Plugin'
        }

        /// <summary>
        /// Test the property 'SolidModel'
        /// </summary>
        [Fact]
        public void SolidModelTest()
        {
            // TODO unit test for the property 'SolidModel'
        }

        /// <summary>
        /// Test the property 'MeshPart'
        /// </summary>
        [Fact]
        public void MeshPartTest()
        {
            // TODO unit test for the property 'MeshPart'
        }

        /// <summary>
        /// Test the property 'HairAccessory'
        /// </summary>
        [Fact]
        public void HairAccessoryTest()
        {
            // TODO unit test for the property 'HairAccessory'
        }

        /// <summary>
        /// Test the property 'FaceAccessory'
        /// </summary>
        [Fact]
        public void FaceAccessoryTest()
        {
            // TODO unit test for the property 'FaceAccessory'
        }

        /// <summary>
        /// Test the property 'NeckAccessory'
        /// </summary>
        [Fact]
        public void NeckAccessoryTest()
        {
            // TODO unit test for the property 'NeckAccessory'
        }

        /// <summary>
        /// Test the property 'ShoulderAccessory'
        /// </summary>
        [Fact]
        public void ShoulderAccessoryTest()
        {
            // TODO unit test for the property 'ShoulderAccessory'
        }

        /// <summary>
        /// Test the property 'FrontAccessory'
        /// </summary>
        [Fact]
        public void FrontAccessoryTest()
        {
            // TODO unit test for the property 'FrontAccessory'
        }

        /// <summary>
        /// Test the property 'BackAccessory'
        /// </summary>
        [Fact]
        public void BackAccessoryTest()
        {
            // TODO unit test for the property 'BackAccessory'
        }

        /// <summary>
        /// Test the property 'WaistAccessory'
        /// </summary>
        [Fact]
        public void WaistAccessoryTest()
        {
            // TODO unit test for the property 'WaistAccessory'
        }

        /// <summary>
        /// Test the property 'ClimbAnimation'
        /// </summary>
        [Fact]
        public void ClimbAnimationTest()
        {
            // TODO unit test for the property 'ClimbAnimation'
        }

        /// <summary>
        /// Test the property 'DeathAnimation'
        /// </summary>
        [Fact]
        public void DeathAnimationTest()
        {
            // TODO unit test for the property 'DeathAnimation'
        }

        /// <summary>
        /// Test the property 'FallAnimation'
        /// </summary>
        [Fact]
        public void FallAnimationTest()
        {
            // TODO unit test for the property 'FallAnimation'
        }

        /// <summary>
        /// Test the property 'IdleAnimation'
        /// </summary>
        [Fact]
        public void IdleAnimationTest()
        {
            // TODO unit test for the property 'IdleAnimation'
        }

        /// <summary>
        /// Test the property 'JumpAnimation'
        /// </summary>
        [Fact]
        public void JumpAnimationTest()
        {
            // TODO unit test for the property 'JumpAnimation'
        }

        /// <summary>
        /// Test the property 'RunAnimation'
        /// </summary>
        [Fact]
        public void RunAnimationTest()
        {
            // TODO unit test for the property 'RunAnimation'
        }

        /// <summary>
        /// Test the property 'SwimAnimation'
        /// </summary>
        [Fact]
        public void SwimAnimationTest()
        {
            // TODO unit test for the property 'SwimAnimation'
        }

        /// <summary>
        /// Test the property 'WalkAnimation'
        /// </summary>
        [Fact]
        public void WalkAnimationTest()
        {
            // TODO unit test for the property 'WalkAnimation'
        }

        /// <summary>
        /// Test the property 'PoseAnimation'
        /// </summary>
        [Fact]
        public void PoseAnimationTest()
        {
            // TODO unit test for the property 'PoseAnimation'
        }

        /// <summary>
        /// Test the property 'LocalizationTableManifest'
        /// </summary>
        [Fact]
        public void LocalizationTableManifestTest()
        {
            // TODO unit test for the property 'LocalizationTableManifest'
        }

        /// <summary>
        /// Test the property 'LocalizationTableTranslation'
        /// </summary>
        [Fact]
        public void LocalizationTableTranslationTest()
        {
            // TODO unit test for the property 'LocalizationTableTranslation'
        }

        /// <summary>
        /// Test the property 'EmoteAnimation'
        /// </summary>
        [Fact]
        public void EmoteAnimationTest()
        {
            // TODO unit test for the property 'EmoteAnimation'
        }

        /// <summary>
        /// Test the property 'Video'
        /// </summary>
        [Fact]
        public void VideoTest()
        {
            // TODO unit test for the property 'Video'
        }

        /// <summary>
        /// Test the property 'TexturePack'
        /// </summary>
        [Fact]
        public void TexturePackTest()
        {
            // TODO unit test for the property 'TexturePack'
        }

        /// <summary>
        /// Test the property 'TShirtAccessory'
        /// </summary>
        [Fact]
        public void TShirtAccessoryTest()
        {
            // TODO unit test for the property 'TShirtAccessory'
        }

        /// <summary>
        /// Test the property 'ShirtAccessory'
        /// </summary>
        [Fact]
        public void ShirtAccessoryTest()
        {
            // TODO unit test for the property 'ShirtAccessory'
        }

        /// <summary>
        /// Test the property 'PantsAccessory'
        /// </summary>
        [Fact]
        public void PantsAccessoryTest()
        {
            // TODO unit test for the property 'PantsAccessory'
        }

        /// <summary>
        /// Test the property 'JacketAccessory'
        /// </summary>
        [Fact]
        public void JacketAccessoryTest()
        {
            // TODO unit test for the property 'JacketAccessory'
        }

        /// <summary>
        /// Test the property 'SweaterAccessory'
        /// </summary>
        [Fact]
        public void SweaterAccessoryTest()
        {
            // TODO unit test for the property 'SweaterAccessory'
        }

        /// <summary>
        /// Test the property 'ShortsAccessory'
        /// </summary>
        [Fact]
        public void ShortsAccessoryTest()
        {
            // TODO unit test for the property 'ShortsAccessory'
        }

        /// <summary>
        /// Test the property 'LeftShoeAccessory'
        /// </summary>
        [Fact]
        public void LeftShoeAccessoryTest()
        {
            // TODO unit test for the property 'LeftShoeAccessory'
        }

        /// <summary>
        /// Test the property 'RightShoeAccessory'
        /// </summary>
        [Fact]
        public void RightShoeAccessoryTest()
        {
            // TODO unit test for the property 'RightShoeAccessory'
        }

        /// <summary>
        /// Test the property 'DressSkirtAccessory'
        /// </summary>
        [Fact]
        public void DressSkirtAccessoryTest()
        {
            // TODO unit test for the property 'DressSkirtAccessory'
        }

        /// <summary>
        /// Test the property 'FontFamily'
        /// </summary>
        [Fact]
        public void FontFamilyTest()
        {
            // TODO unit test for the property 'FontFamily'
        }

        /// <summary>
        /// Test the property 'FontFace'
        /// </summary>
        [Fact]
        public void FontFaceTest()
        {
            // TODO unit test for the property 'FontFace'
        }

        /// <summary>
        /// Test the property 'MeshHiddenSurfaceRemoval'
        /// </summary>
        [Fact]
        public void MeshHiddenSurfaceRemovalTest()
        {
            // TODO unit test for the property 'MeshHiddenSurfaceRemoval'
        }

        /// <summary>
        /// Test the property 'EyebrowAccessory'
        /// </summary>
        [Fact]
        public void EyebrowAccessoryTest()
        {
            // TODO unit test for the property 'EyebrowAccessory'
        }

        /// <summary>
        /// Test the property 'EyelashAccessory'
        /// </summary>
        [Fact]
        public void EyelashAccessoryTest()
        {
            // TODO unit test for the property 'EyelashAccessory'
        }

        /// <summary>
        /// Test the property 'MoodAnimation'
        /// </summary>
        [Fact]
        public void MoodAnimationTest()
        {
            // TODO unit test for the property 'MoodAnimation'
        }

        /// <summary>
        /// Test the property 'DynamicHead'
        /// </summary>
        [Fact]
        public void DynamicHeadTest()
        {
            // TODO unit test for the property 'DynamicHead'
        }

        /// <summary>
        /// Test the property 'CodeSnippet'
        /// </summary>
        [Fact]
        public void CodeSnippetTest()
        {
            // TODO unit test for the property 'CodeSnippet'
        }
    }
}
