/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsAvatarApiSuccessResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsAvatarApiSuccessResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsAvatarApiSuccessResponse
        //private RobloxApiAvatarModelsAvatarApiSuccessResponse instance;

        public RobloxApiAvatarModelsAvatarApiSuccessResponseTests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsAvatarApiSuccessResponse
            //instance = new RobloxApiAvatarModelsAvatarApiSuccessResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsAvatarApiSuccessResponse
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsAvatarApiSuccessResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsAvatarApiSuccessResponse
            //Assert.IsType<RobloxApiAvatarModelsAvatarApiSuccessResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
    }
}
