/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsAssetMetaModelV1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsAssetMetaModelV1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsAssetMetaModelV1
        //private RobloxApiAvatarModelsAssetMetaModelV1 instance;

        public RobloxApiAvatarModelsAssetMetaModelV1Tests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsAssetMetaModelV1
            //instance = new RobloxApiAvatarModelsAssetMetaModelV1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsAssetMetaModelV1
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsAssetMetaModelV1InstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsAssetMetaModelV1
            //Assert.IsType<RobloxApiAvatarModelsAssetMetaModelV1>(instance);
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }

        /// <summary>
        /// Test the property 'Puffiness'
        /// </summary>
        [Fact]
        public void PuffinessTest()
        {
            // TODO unit test for the property 'Puffiness'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

        /// <summary>
        /// Test the property 'Rotation'
        /// </summary>
        [Fact]
        public void RotationTest()
        {
            // TODO unit test for the property 'Rotation'
        }

        /// <summary>
        /// Test the property 'Scale'
        /// </summary>
        [Fact]
        public void ScaleTest()
        {
            // TODO unit test for the property 'Scale'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
