/*
 * Thumbnails Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxThumbnailsCommonThumbnailImageParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxThumbnailsCommonThumbnailImageParametersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxThumbnailsCommonThumbnailImageParameters
        //private RobloxThumbnailsCommonThumbnailImageParameters instance;

        public RobloxThumbnailsCommonThumbnailImageParametersTests()
        {
            // TODO uncomment below to create an instance of RobloxThumbnailsCommonThumbnailImageParameters
            //instance = new RobloxThumbnailsCommonThumbnailImageParameters();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxThumbnailsCommonThumbnailImageParameters
        /// </summary>
        [Fact]
        public void RobloxThumbnailsCommonThumbnailImageParametersInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxThumbnailsCommonThumbnailImageParameters
            //Assert.IsType<RobloxThumbnailsCommonThumbnailImageParameters>(instance);
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }

        /// <summary>
        /// Test the property 'IsCircular'
        /// </summary>
        [Fact]
        public void IsCircularTest()
        {
            // TODO unit test for the property 'IsCircular'
        }
    }
}
