/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxWebResponsesAvatarScaleModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxWebResponsesAvatarScaleModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxWebResponsesAvatarScaleModel
        //private RobloxWebResponsesAvatarScaleModel instance;

        public RobloxWebResponsesAvatarScaleModelTests()
        {
            // TODO uncomment below to create an instance of RobloxWebResponsesAvatarScaleModel
            //instance = new RobloxWebResponsesAvatarScaleModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxWebResponsesAvatarScaleModel
        /// </summary>
        [Fact]
        public void RobloxWebResponsesAvatarScaleModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxWebResponsesAvatarScaleModel
            //Assert.IsType<RobloxWebResponsesAvatarScaleModel>(instance);
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Head'
        /// </summary>
        [Fact]
        public void HeadTest()
        {
            // TODO unit test for the property 'Head'
        }

        /// <summary>
        /// Test the property 'Depth'
        /// </summary>
        [Fact]
        public void DepthTest()
        {
            // TODO unit test for the property 'Depth'
        }

        /// <summary>
        /// Test the property 'Proportion'
        /// </summary>
        [Fact]
        public void ProportionTest()
        {
            // TODO unit test for the property 'Proportion'
        }

        /// <summary>
        /// Test the property 'BodyType'
        /// </summary>
        [Fact]
        public void BodyTypeTest()
        {
            // TODO unit test for the property 'BodyType'
        }
    }
}
