/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsEmoteResponseModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsEmoteResponseModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsEmoteResponseModel
        //private RobloxApiAvatarModelsEmoteResponseModel instance;

        public RobloxApiAvatarModelsEmoteResponseModelTests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsEmoteResponseModel
            //instance = new RobloxApiAvatarModelsEmoteResponseModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsEmoteResponseModel
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsEmoteResponseModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsEmoteResponseModel
            //Assert.IsType<RobloxApiAvatarModelsEmoteResponseModel>(instance);
        }

        /// <summary>
        /// Test the property 'AssetId'
        /// </summary>
        [Fact]
        public void AssetIdTest()
        {
            // TODO unit test for the property 'AssetId'
        }

        /// <summary>
        /// Test the property 'AssetName'
        /// </summary>
        [Fact]
        public void AssetNameTest()
        {
            // TODO unit test for the property 'AssetName'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
    }
}
