/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsBodyColorModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsBodyColorModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsBodyColorModel
        //private RobloxApiAvatarModelsBodyColorModel instance;

        public RobloxApiAvatarModelsBodyColorModelTests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsBodyColorModel
            //instance = new RobloxApiAvatarModelsBodyColorModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsBodyColorModel
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsBodyColorModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsBodyColorModel
            //Assert.IsType<RobloxApiAvatarModelsBodyColorModel>(instance);
        }

        /// <summary>
        /// Test the property 'BrickColorId'
        /// </summary>
        [Fact]
        public void BrickColorIdTest()
        {
            // TODO unit test for the property 'BrickColorId'
        }

        /// <summary>
        /// Test the property 'HexColor'
        /// </summary>
        [Fact]
        public void HexColorTest()
        {
            // TODO unit test for the property 'HexColor'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
