/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsAssetModelV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsAssetModelV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsAssetModelV2
        //private RobloxApiAvatarModelsAssetModelV2 instance;

        public RobloxApiAvatarModelsAssetModelV2Tests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsAssetModelV2
            //instance = new RobloxApiAvatarModelsAssetModelV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsAssetModelV2
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsAssetModelV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsAssetModelV2
            //Assert.IsType<RobloxApiAvatarModelsAssetModelV2>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'AssetType'
        /// </summary>
        [Fact]
        public void AssetTypeTest()
        {
            // TODO unit test for the property 'AssetType'
        }

        /// <summary>
        /// Test the property 'CurrentVersionId'
        /// </summary>
        [Fact]
        public void CurrentVersionIdTest()
        {
            // TODO unit test for the property 'CurrentVersionId'
        }

        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }
    }
}
