/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsBodyColorsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsBodyColorsModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsBodyColorsModel
        //private RobloxApiAvatarModelsBodyColorsModel instance;

        public RobloxApiAvatarModelsBodyColorsModelTests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsBodyColorsModel
            //instance = new RobloxApiAvatarModelsBodyColorsModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsBodyColorsModel
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsBodyColorsModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsBodyColorsModel
            //Assert.IsType<RobloxApiAvatarModelsBodyColorsModel>(instance);
        }

        /// <summary>
        /// Test the property 'HeadColorId'
        /// </summary>
        [Fact]
        public void HeadColorIdTest()
        {
            // TODO unit test for the property 'HeadColorId'
        }

        /// <summary>
        /// Test the property 'TorsoColorId'
        /// </summary>
        [Fact]
        public void TorsoColorIdTest()
        {
            // TODO unit test for the property 'TorsoColorId'
        }

        /// <summary>
        /// Test the property 'RightArmColorId'
        /// </summary>
        [Fact]
        public void RightArmColorIdTest()
        {
            // TODO unit test for the property 'RightArmColorId'
        }

        /// <summary>
        /// Test the property 'LeftArmColorId'
        /// </summary>
        [Fact]
        public void LeftArmColorIdTest()
        {
            // TODO unit test for the property 'LeftArmColorId'
        }

        /// <summary>
        /// Test the property 'RightLegColorId'
        /// </summary>
        [Fact]
        public void RightLegColorIdTest()
        {
            // TODO unit test for the property 'RightLegColorId'
        }

        /// <summary>
        /// Test the property 'LeftLegColorId'
        /// </summary>
        [Fact]
        public void LeftLegColorIdTest()
        {
            // TODO unit test for the property 'LeftLegColorId'
        }
    }
}
