/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsOutfitDetailsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsOutfitDetailsModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsOutfitDetailsModel
        //private RobloxApiAvatarModelsOutfitDetailsModel instance;

        public RobloxApiAvatarModelsOutfitDetailsModelTests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsOutfitDetailsModel
            //instance = new RobloxApiAvatarModelsOutfitDetailsModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsOutfitDetailsModel
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsOutfitDetailsModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsOutfitDetailsModel
            //Assert.IsType<RobloxApiAvatarModelsOutfitDetailsModel>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'UniverseId'
        /// </summary>
        [Fact]
        public void UniverseIdTest()
        {
            // TODO unit test for the property 'UniverseId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Assets'
        /// </summary>
        [Fact]
        public void AssetsTest()
        {
            // TODO unit test for the property 'Assets'
        }

        /// <summary>
        /// Test the property 'BodyColors'
        /// </summary>
        [Fact]
        public void BodyColorsTest()
        {
            // TODO unit test for the property 'BodyColors'
        }

        /// <summary>
        /// Test the property 'Scale'
        /// </summary>
        [Fact]
        public void ScaleTest()
        {
            // TODO unit test for the property 'Scale'
        }

        /// <summary>
        /// Test the property 'PlayerAvatarType'
        /// </summary>
        [Fact]
        public void PlayerAvatarTypeTest()
        {
            // TODO unit test for the property 'PlayerAvatarType'
        }

        /// <summary>
        /// Test the property 'OutfitType'
        /// </summary>
        [Fact]
        public void OutfitTypeTest()
        {
            // TODO unit test for the property 'OutfitType'
        }

        /// <summary>
        /// Test the property 'IsEditable'
        /// </summary>
        [Fact]
        public void IsEditableTest()
        {
            // TODO unit test for the property 'IsEditable'
        }

        /// <summary>
        /// Test the property 'ModerationStatus'
        /// </summary>
        [Fact]
        public void ModerationStatusTest()
        {
            // TODO unit test for the property 'ModerationStatus'
        }
    }
}
