/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsOutfitUpdateModelV1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsOutfitUpdateModelV1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsOutfitUpdateModelV1
        //private RobloxApiAvatarModelsOutfitUpdateModelV1 instance;

        public RobloxApiAvatarModelsOutfitUpdateModelV1Tests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsOutfitUpdateModelV1
            //instance = new RobloxApiAvatarModelsOutfitUpdateModelV1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsOutfitUpdateModelV1
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsOutfitUpdateModelV1InstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsOutfitUpdateModelV1
            //Assert.IsType<RobloxApiAvatarModelsOutfitUpdateModelV1>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'BodyColors'
        /// </summary>
        [Fact]
        public void BodyColorsTest()
        {
            // TODO unit test for the property 'BodyColors'
        }

        /// <summary>
        /// Test the property 'AssetIds'
        /// </summary>
        [Fact]
        public void AssetIdsTest()
        {
            // TODO unit test for the property 'AssetIds'
        }

        /// <summary>
        /// Test the property 'Scale'
        /// </summary>
        [Fact]
        public void ScaleTest()
        {
            // TODO unit test for the property 'Scale'
        }

        /// <summary>
        /// Test the property 'PlayerAvatarType'
        /// </summary>
        [Fact]
        public void PlayerAvatarTypeTest()
        {
            // TODO unit test for the property 'PlayerAvatarType'
        }

        /// <summary>
        /// Test the property 'OutfitType'
        /// </summary>
        [Fact]
        public void OutfitTypeTest()
        {
            // TODO unit test for the property 'OutfitType'
        }
    }
}
