/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsAssetIdListModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsAssetIdListModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsAssetIdListModel
        //private RobloxApiAvatarModelsAssetIdListModel instance;

        public RobloxApiAvatarModelsAssetIdListModelTests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsAssetIdListModel
            //instance = new RobloxApiAvatarModelsAssetIdListModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsAssetIdListModel
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsAssetIdListModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsAssetIdListModel
            //Assert.IsType<RobloxApiAvatarModelsAssetIdListModel>(instance);
        }

        /// <summary>
        /// Test the property 'AssetIds'
        /// </summary>
        [Fact]
        public void AssetIdsTest()
        {
            // TODO unit test for the property 'AssetIds'
        }
    }
}
