/*
 * Thumbnails Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxThumbnailsCommonFormatType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxThumbnailsCommonFormatTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxThumbnailsCommonFormatType
        //private RobloxThumbnailsCommonFormatType instance;

        public RobloxThumbnailsCommonFormatTypeTests()
        {
            // TODO uncomment below to create an instance of RobloxThumbnailsCommonFormatType
            //instance = new RobloxThumbnailsCommonFormatType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxThumbnailsCommonFormatType
        /// </summary>
        [Fact]
        public void RobloxThumbnailsCommonFormatTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxThumbnailsCommonFormatType
            //Assert.IsType<RobloxThumbnailsCommonFormatType>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
