/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsAvatarModelV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsAvatarModelV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsAvatarModelV2
        //private RobloxApiAvatarModelsAvatarModelV2 instance;

        public RobloxApiAvatarModelsAvatarModelV2Tests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsAvatarModelV2
            //instance = new RobloxApiAvatarModelsAvatarModelV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsAvatarModelV2
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsAvatarModelV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsAvatarModelV2
            //Assert.IsType<RobloxApiAvatarModelsAvatarModelV2>(instance);
        }

        /// <summary>
        /// Test the property 'Scales'
        /// </summary>
        [Fact]
        public void ScalesTest()
        {
            // TODO unit test for the property 'Scales'
        }

        /// <summary>
        /// Test the property 'PlayerAvatarType'
        /// </summary>
        [Fact]
        public void PlayerAvatarTypeTest()
        {
            // TODO unit test for the property 'PlayerAvatarType'
        }

        /// <summary>
        /// Test the property 'BodyColors'
        /// </summary>
        [Fact]
        public void BodyColorsTest()
        {
            // TODO unit test for the property 'BodyColors'
        }

        /// <summary>
        /// Test the property 'Assets'
        /// </summary>
        [Fact]
        public void AssetsTest()
        {
            // TODO unit test for the property 'Assets'
        }

        /// <summary>
        /// Test the property 'DefaultShirtApplied'
        /// </summary>
        [Fact]
        public void DefaultShirtAppliedTest()
        {
            // TODO unit test for the property 'DefaultShirtApplied'
        }

        /// <summary>
        /// Test the property 'DefaultPantsApplied'
        /// </summary>
        [Fact]
        public void DefaultPantsAppliedTest()
        {
            // TODO unit test for the property 'DefaultPantsApplied'
        }

        /// <summary>
        /// Test the property 'Emotes'
        /// </summary>
        [Fact]
        public void EmotesTest()
        {
            // TODO unit test for the property 'Emotes'
        }
    }
}
