/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Avatar.ApiV1.Model;
using Knedlex.Roblox.Avatar.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Avatar.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxApiAvatarModelsDefaultClothingAssets
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxApiAvatarModelsDefaultClothingAssetsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxApiAvatarModelsDefaultClothingAssets
        //private RobloxApiAvatarModelsDefaultClothingAssets instance;

        public RobloxApiAvatarModelsDefaultClothingAssetsTests()
        {
            // TODO uncomment below to create an instance of RobloxApiAvatarModelsDefaultClothingAssets
            //instance = new RobloxApiAvatarModelsDefaultClothingAssets();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxApiAvatarModelsDefaultClothingAssets
        /// </summary>
        [Fact]
        public void RobloxApiAvatarModelsDefaultClothingAssetsInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxApiAvatarModelsDefaultClothingAssets
            //Assert.IsType<RobloxApiAvatarModelsDefaultClothingAssets>(instance);
        }

        /// <summary>
        /// Test the property 'DefaultShirtAssetIds'
        /// </summary>
        [Fact]
        public void DefaultShirtAssetIdsTest()
        {
            // TODO unit test for the property 'DefaultShirtAssetIds'
        }

        /// <summary>
        /// Test the property 'DefaultPantAssetIds'
        /// </summary>
        [Fact]
        public void DefaultPantAssetIdsTest()
        {
            // TODO unit test for the property 'DefaultPantAssetIds'
        }
    }
}
