/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Knedlex.Roblox.Avatar.ApiV1.Client.OpenAPIDateConverter;

namespace Knedlex.Roblox.Avatar.ApiV1.Model
{
    /// <summary>
    /// AvatarCommonModelsAccessoryScaleModel
    /// </summary>
    [DataContract(Name = "Avatar.Common.Models.AccessoryScaleModel")]
    public partial class AvatarCommonModelsAccessoryScaleModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AvatarCommonModelsAccessoryScaleModel" /> class.
        /// </summary>
        /// <param name="xScale">xScale.</param>
        /// <param name="yScale">yScale.</param>
        /// <param name="zScale">zScale.</param>
        public AvatarCommonModelsAccessoryScaleModel(double xScale = default(double), double yScale = default(double), double zScale = default(double))
        {
            this.XScale = xScale;
            this.YScale = yScale;
            this.ZScale = zScale;
        }

        /// <summary>
        /// Gets or Sets XScale
        /// </summary>
        [DataMember(Name = "xScale", EmitDefaultValue = false)]
        public double XScale { get; set; }

        /// <summary>
        /// Gets or Sets YScale
        /// </summary>
        [DataMember(Name = "yScale", EmitDefaultValue = false)]
        public double YScale { get; set; }

        /// <summary>
        /// Gets or Sets ZScale
        /// </summary>
        [DataMember(Name = "zScale", EmitDefaultValue = false)]
        public double ZScale { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AvatarCommonModelsAccessoryScaleModel {\n");
            sb.Append("  XScale: ").Append(XScale).Append("\n");
            sb.Append("  YScale: ").Append(YScale).Append("\n");
            sb.Append("  ZScale: ").Append(ZScale).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
