/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Knedlex.Roblox.Avatar.ApiV1.Client.OpenAPIDateConverter;

namespace Knedlex.Roblox.Avatar.ApiV1.Model
{
    /// <summary>
    /// AvatarCommonModelsAccessoryPositionModel
    /// </summary>
    [DataContract(Name = "Avatar.Common.Models.AccessoryPositionModel")]
    public partial class AvatarCommonModelsAccessoryPositionModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AvatarCommonModelsAccessoryPositionModel" /> class.
        /// </summary>
        /// <param name="xPosition">xPosition.</param>
        /// <param name="yPosition">yPosition.</param>
        /// <param name="zPosition">zPosition.</param>
        public AvatarCommonModelsAccessoryPositionModel(double xPosition = default(double), double yPosition = default(double), double zPosition = default(double))
        {
            this.XPosition = xPosition;
            this.YPosition = yPosition;
            this.ZPosition = zPosition;
        }

        /// <summary>
        /// Gets or Sets XPosition
        /// </summary>
        [DataMember(Name = "xPosition", EmitDefaultValue = false)]
        public double XPosition { get; set; }

        /// <summary>
        /// Gets or Sets YPosition
        /// </summary>
        [DataMember(Name = "yPosition", EmitDefaultValue = false)]
        public double YPosition { get; set; }

        /// <summary>
        /// Gets or Sets ZPosition
        /// </summary>
        [DataMember(Name = "zPosition", EmitDefaultValue = false)]
        public double ZPosition { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AvatarCommonModelsAccessoryPositionModel {\n");
            sb.Append("  XPosition: ").Append(XPosition).Append("\n");
            sb.Append("  YPosition: ").Append(YPosition).Append("\n");
            sb.Append("  ZPosition: ").Append(ZPosition).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
