/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Knedlex.Roblox.Avatar.ApiV1.Client.OpenAPIDateConverter;

namespace Knedlex.Roblox.Avatar.ApiV1.Model
{
    /// <summary>
    /// AvatarCommonModelsAccessoryRefinementModel
    /// </summary>
    [DataContract(Name = "Avatar.Common.Models.AccessoryRefinementModel")]
    public partial class AvatarCommonModelsAccessoryRefinementModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AvatarCommonModelsAccessoryRefinementModel" /> class.
        /// </summary>
        /// <param name="position">position.</param>
        /// <param name="rotation">rotation.</param>
        /// <param name="scale">scale.</param>
        public AvatarCommonModelsAccessoryRefinementModel(AvatarCommonModelsAccessoryPositionModel position = default(AvatarCommonModelsAccessoryPositionModel), AvatarCommonModelsAccessoryRotationModel rotation = default(AvatarCommonModelsAccessoryRotationModel), AvatarCommonModelsAccessoryScaleModel scale = default(AvatarCommonModelsAccessoryScaleModel))
        {
            this.Position = position;
            this.Rotation = rotation;
            this.Scale = scale;
        }

        /// <summary>
        /// Gets or Sets Position
        /// </summary>
        [DataMember(Name = "position", EmitDefaultValue = false)]
        public AvatarCommonModelsAccessoryPositionModel Position { get; set; }

        /// <summary>
        /// Gets or Sets Rotation
        /// </summary>
        [DataMember(Name = "rotation", EmitDefaultValue = false)]
        public AvatarCommonModelsAccessoryRotationModel Rotation { get; set; }

        /// <summary>
        /// Gets or Sets Scale
        /// </summary>
        [DataMember(Name = "scale", EmitDefaultValue = false)]
        public AvatarCommonModelsAccessoryScaleModel Scale { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AvatarCommonModelsAccessoryRefinementModel {\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  Rotation: ").Append(Rotation).Append("\n");
            sb.Append("  Scale: ").Append(Scale).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
