/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Knedlex.Roblox.Avatar.ApiV1.Client.OpenAPIDateConverter;

namespace Knedlex.Roblox.Avatar.ApiV1.Model
{
    /// <summary>
    /// Exhaustive model denoting all possible metadata fields of an asset
    /// </summary>
    [DataContract(Name = "Roblox.Api.Avatar.Models.AssetMetaModelV1")]
    public partial class RobloxApiAvatarModelsAssetMetaModelV1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RobloxApiAvatarModelsAssetMetaModelV1" /> class.
        /// </summary>
        /// <param name="order">Layered-clothing order.</param>
        /// <param name="puffiness">Layered-clothing puffiness.</param>
        /// <param name="position">position.</param>
        /// <param name="rotation">rotation.</param>
        /// <param name="scale">scale.</param>
        /// <param name="varVersion">Client-authoritative meta model format version  - default is always 1.</param>
        public RobloxApiAvatarModelsAssetMetaModelV1(int order = default(int), float puffiness = default(float), RobloxAvatarcoreSharedV3Beta1AssetPosition position = default(RobloxAvatarcoreSharedV3Beta1AssetPosition), RobloxAvatarcoreSharedV3Beta1AssetRotation rotation = default(RobloxAvatarcoreSharedV3Beta1AssetRotation), RobloxAvatarcoreSharedV3Beta1AssetScale scale = default(RobloxAvatarcoreSharedV3Beta1AssetScale), int varVersion = default(int))
        {
            this.Order = order;
            this.Puffiness = puffiness;
            this.Position = position;
            this.Rotation = rotation;
            this.Scale = scale;
            this.VarVersion = varVersion;
        }

        /// <summary>
        /// Layered-clothing order
        /// </summary>
        /// <value>Layered-clothing order</value>
        [DataMember(Name = "order", EmitDefaultValue = false)]
        public int Order { get; set; }

        /// <summary>
        /// Layered-clothing puffiness
        /// </summary>
        /// <value>Layered-clothing puffiness</value>
        [DataMember(Name = "puffiness", EmitDefaultValue = false)]
        public float Puffiness { get; set; }

        /// <summary>
        /// Gets or Sets Position
        /// </summary>
        [DataMember(Name = "position", EmitDefaultValue = false)]
        public RobloxAvatarcoreSharedV3Beta1AssetPosition Position { get; set; }

        /// <summary>
        /// Gets or Sets Rotation
        /// </summary>
        [DataMember(Name = "rotation", EmitDefaultValue = false)]
        public RobloxAvatarcoreSharedV3Beta1AssetRotation Rotation { get; set; }

        /// <summary>
        /// Gets or Sets Scale
        /// </summary>
        [DataMember(Name = "scale", EmitDefaultValue = false)]
        public RobloxAvatarcoreSharedV3Beta1AssetScale Scale { get; set; }

        /// <summary>
        /// Client-authoritative meta model format version  - default is always 1
        /// </summary>
        /// <value>Client-authoritative meta model format version  - default is always 1</value>
        [DataMember(Name = "version", EmitDefaultValue = false)]
        public int VarVersion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RobloxApiAvatarModelsAssetMetaModelV1 {\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("  Puffiness: ").Append(Puffiness).Append("\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  Rotation: ").Append(Rotation).Append("\n");
            sb.Append("  Scale: ").Append(Scale).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
