/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Knedlex.Roblox.Avatar.ApiV1.Client.OpenAPIDateConverter;

namespace Knedlex.Roblox.Avatar.ApiV1.Model
{
    /// <summary>
    /// A model container BrickColor ids for each body part.
    /// </summary>
    [DataContract(Name = "Roblox.Api.Avatar.Models.BodyColorModel")]
    public partial class RobloxApiAvatarModelsBodyColorModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RobloxApiAvatarModelsBodyColorModel" /> class.
        /// </summary>
        /// <param name="brickColorId">The BrickColor id.</param>
        /// <param name="hexColor">The hex color, e.g. #FFFFFF.</param>
        /// <param name="name">The name of the BrickColor.</param>
        public RobloxApiAvatarModelsBodyColorModel(int brickColorId = default(int), string hexColor = default(string), string name = default(string))
        {
            this.BrickColorId = brickColorId;
            this.HexColor = hexColor;
            this.Name = name;
        }

        /// <summary>
        /// The BrickColor id
        /// </summary>
        /// <value>The BrickColor id</value>
        [DataMember(Name = "brickColorId", EmitDefaultValue = false)]
        public int BrickColorId { get; set; }

        /// <summary>
        /// The hex color, e.g. #FFFFFF
        /// </summary>
        /// <value>The hex color, e.g. #FFFFFF</value>
        [DataMember(Name = "hexColor", EmitDefaultValue = false)]
        public string HexColor { get; set; }

        /// <summary>
        /// The name of the BrickColor
        /// </summary>
        /// <value>The name of the BrickColor</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RobloxApiAvatarModelsBodyColorModel {\n");
            sb.Append("  BrickColorId: ").Append(BrickColorId).Append("\n");
            sb.Append("  HexColor: ").Append(HexColor).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
