/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Knedlex.Roblox.Avatar.ApiV1.Client.OpenAPIDateConverter;

namespace Knedlex.Roblox.Avatar.ApiV1.Model
{
    /// <summary>
    /// A model containing details about avatar-related business rules
    /// </summary>
    [DataContract(Name = "Roblox.Api.Avatar.Models.DefaultClothingAssets")]
    public partial class RobloxApiAvatarModelsDefaultClothingAssets : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RobloxApiAvatarModelsDefaultClothingAssets" /> class.
        /// </summary>
        /// <param name="defaultShirtAssetIds">List of asset Ids used to equip shirts for default clothing when the avatar appears nude..</param>
        /// <param name="defaultPantAssetIds">List of asset Ids used to equip pants for default clothing when the avatar appears nude..</param>
        public RobloxApiAvatarModelsDefaultClothingAssets(List<long> defaultShirtAssetIds = default(List<long>), List<long> defaultPantAssetIds = default(List<long>))
        {
            this.DefaultShirtAssetIds = defaultShirtAssetIds;
            this.DefaultPantAssetIds = defaultPantAssetIds;
        }

        /// <summary>
        /// List of asset Ids used to equip shirts for default clothing when the avatar appears nude.
        /// </summary>
        /// <value>List of asset Ids used to equip shirts for default clothing when the avatar appears nude.</value>
        [DataMember(Name = "defaultShirtAssetIds", EmitDefaultValue = false)]
        public List<long> DefaultShirtAssetIds { get; set; }

        /// <summary>
        /// List of asset Ids used to equip pants for default clothing when the avatar appears nude.
        /// </summary>
        /// <value>List of asset Ids used to equip pants for default clothing when the avatar appears nude.</value>
        [DataMember(Name = "defaultPantAssetIds", EmitDefaultValue = false)]
        public List<long> DefaultPantAssetIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RobloxApiAvatarModelsDefaultClothingAssets {\n");
            sb.Append("  DefaultShirtAssetIds: ").Append(DefaultShirtAssetIds).Append("\n");
            sb.Append("  DefaultPantAssetIds: ").Append(DefaultPantAssetIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
