/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Knedlex.Roblox.Avatar.ApiV1.Client.OpenAPIDateConverter;

namespace Knedlex.Roblox.Avatar.ApiV1.Model
{
    /// <summary>
    /// A model containing details about an avatar
    /// </summary>
    [DataContract(Name = "Roblox.Api.Avatar.Models.AvatarModelV2")]
    public partial class RobloxApiAvatarModelsAvatarModelV2 : IValidatableObject
    {
        /// <summary>
        /// The avatar type [&#39;R6&#39; &#x3D; 1, &#39;R15&#39; &#x3D; 3]
        /// </summary>
        /// <value>The avatar type [&#39;R6&#39; &#x3D; 1, &#39;R15&#39; &#x3D; 3]</value>
        public enum PlayerAvatarTypeEnum
        {
            /// <summary>
            /// Enum NUMBER_1 for value: 1
            /// </summary>
            NUMBER_1 = 1,

            /// <summary>
            /// Enum NUMBER_3 for value: 3
            /// </summary>
            NUMBER_3 = 3
        }


        /// <summary>
        /// The avatar type [&#39;R6&#39; &#x3D; 1, &#39;R15&#39; &#x3D; 3]
        /// </summary>
        /// <value>The avatar type [&#39;R6&#39; &#x3D; 1, &#39;R15&#39; &#x3D; 3]</value>
        [DataMember(Name = "playerAvatarType", EmitDefaultValue = false)]
        public PlayerAvatarTypeEnum? PlayerAvatarType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RobloxApiAvatarModelsAvatarModelV2" /> class.
        /// </summary>
        /// <param name="scales">scales.</param>
        /// <param name="playerAvatarType">The avatar type [&#39;R6&#39; &#x3D; 1, &#39;R15&#39; &#x3D; 3].</param>
        /// <param name="bodyColors">bodyColors.</param>
        /// <param name="assets">The assets worn on the character.</param>
        /// <param name="defaultShirtApplied">Whether default clothing has been applied to this avatar..</param>
        /// <param name="defaultPantsApplied">Whether default clothing has been applied to this avatar..</param>
        /// <param name="emotes">The emotes on the character.</param>
        public RobloxApiAvatarModelsAvatarModelV2(RobloxWebResponsesAvatarScaleModel scales = default(RobloxWebResponsesAvatarScaleModel), PlayerAvatarTypeEnum? playerAvatarType = default(PlayerAvatarTypeEnum?), RobloxApiAvatarModelsBodyColorsModel bodyColors = default(RobloxApiAvatarModelsBodyColorsModel), List<RobloxApiAvatarModelsAssetModelV2> assets = default(List<RobloxApiAvatarModelsAssetModelV2>), bool defaultShirtApplied = default(bool), bool defaultPantsApplied = default(bool), List<RobloxApiAvatarModelsEmoteResponseModel> emotes = default(List<RobloxApiAvatarModelsEmoteResponseModel>))
        {
            this.Scales = scales;
            this.PlayerAvatarType = playerAvatarType;
            this.BodyColors = bodyColors;
            this.Assets = assets;
            this.DefaultShirtApplied = defaultShirtApplied;
            this.DefaultPantsApplied = defaultPantsApplied;
            this.Emotes = emotes;
        }

        /// <summary>
        /// Gets or Sets Scales
        /// </summary>
        [DataMember(Name = "scales", EmitDefaultValue = false)]
        public RobloxWebResponsesAvatarScaleModel Scales { get; set; }

        /// <summary>
        /// Gets or Sets BodyColors
        /// </summary>
        [DataMember(Name = "bodyColors", EmitDefaultValue = false)]
        public RobloxApiAvatarModelsBodyColorsModel BodyColors { get; set; }

        /// <summary>
        /// The assets worn on the character
        /// </summary>
        /// <value>The assets worn on the character</value>
        [DataMember(Name = "assets", EmitDefaultValue = false)]
        public List<RobloxApiAvatarModelsAssetModelV2> Assets { get; set; }

        /// <summary>
        /// Whether default clothing has been applied to this avatar.
        /// </summary>
        /// <value>Whether default clothing has been applied to this avatar.</value>
        [DataMember(Name = "defaultShirtApplied", EmitDefaultValue = true)]
        public bool DefaultShirtApplied { get; set; }

        /// <summary>
        /// Whether default clothing has been applied to this avatar.
        /// </summary>
        /// <value>Whether default clothing has been applied to this avatar.</value>
        [DataMember(Name = "defaultPantsApplied", EmitDefaultValue = true)]
        public bool DefaultPantsApplied { get; set; }

        /// <summary>
        /// The emotes on the character
        /// </summary>
        /// <value>The emotes on the character</value>
        [DataMember(Name = "emotes", EmitDefaultValue = false)]
        public List<RobloxApiAvatarModelsEmoteResponseModel> Emotes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RobloxApiAvatarModelsAvatarModelV2 {\n");
            sb.Append("  Scales: ").Append(Scales).Append("\n");
            sb.Append("  PlayerAvatarType: ").Append(PlayerAvatarType).Append("\n");
            sb.Append("  BodyColors: ").Append(BodyColors).Append("\n");
            sb.Append("  Assets: ").Append(Assets).Append("\n");
            sb.Append("  DefaultShirtApplied: ").Append(DefaultShirtApplied).Append("\n");
            sb.Append("  DefaultPantsApplied: ").Append(DefaultPantsApplied).Append("\n");
            sb.Append("  Emotes: ").Append(Emotes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
