/*
 * Thumbnails Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Knedlex.Roblox.Avatar.ApiV1.Client.OpenAPIDateConverter;

namespace Knedlex.Roblox.Avatar.ApiV1.Model
{
    /// <summary>
    /// RobloxThumbnailsCommonThumbnailImageParameters
    /// </summary>
    [DataContract(Name = "Roblox.Thumbnails.Common.ThumbnailImageParameters")]
    public partial class RobloxThumbnailsCommonThumbnailImageParameters : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RobloxThumbnailsCommonThumbnailImageParameters" /> class.
        /// </summary>
        /// <param name="width">width.</param>
        /// <param name="height">height.</param>
        /// <param name="format">format.</param>
        /// <param name="isCircular">isCircular.</param>
        public RobloxThumbnailsCommonThumbnailImageParameters(int width = default(int), int height = default(int), RobloxThumbnailsCommonFormatType format = default(RobloxThumbnailsCommonFormatType), bool isCircular = default(bool))
        {
            this.Width = width;
            this.Height = height;
            this.Format = format;
            this.IsCircular = isCircular;
        }

        /// <summary>
        /// Gets or Sets Width
        /// </summary>
        [DataMember(Name = "Width", EmitDefaultValue = false)]
        public int Width { get; set; }

        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name = "Height", EmitDefaultValue = false)]
        public int Height { get; set; }

        /// <summary>
        /// Gets or Sets Format
        /// </summary>
        [DataMember(Name = "Format", EmitDefaultValue = false)]
        public RobloxThumbnailsCommonFormatType Format { get; set; }

        /// <summary>
        /// Gets or Sets IsCircular
        /// </summary>
        [DataMember(Name = "IsCircular", EmitDefaultValue = true)]
        public bool IsCircular { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RobloxThumbnailsCommonThumbnailImageParameters {\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  IsCircular: ").Append(IsCircular).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
