/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Knedlex.Roblox.Avatar.ApiV1.Client.OpenAPIDateConverter;

namespace Knedlex.Roblox.Avatar.ApiV1.Model
{
    /// <summary>
    /// A model that contains a playerAvatarType
    /// </summary>
    [DataContract(Name = "Roblox.Api.Avatar.Models.PlayerAvatarTypeModel")]
    public partial class RobloxApiAvatarModelsPlayerAvatarTypeModel : IValidatableObject
    {
        /// <summary>
        /// The playerAvatarType [&#39;R6&#39; &#x3D; 1, &#39;R15&#39; &#x3D; 3]
        /// </summary>
        /// <value>The playerAvatarType [&#39;R6&#39; &#x3D; 1, &#39;R15&#39; &#x3D; 3]</value>
        public enum PlayerAvatarTypeEnum
        {
            /// <summary>
            /// Enum NUMBER_1 for value: 1
            /// </summary>
            NUMBER_1 = 1,

            /// <summary>
            /// Enum NUMBER_3 for value: 3
            /// </summary>
            NUMBER_3 = 3
        }


        /// <summary>
        /// The playerAvatarType [&#39;R6&#39; &#x3D; 1, &#39;R15&#39; &#x3D; 3]
        /// </summary>
        /// <value>The playerAvatarType [&#39;R6&#39; &#x3D; 1, &#39;R15&#39; &#x3D; 3]</value>
        [DataMember(Name = "playerAvatarType", EmitDefaultValue = false)]
        public PlayerAvatarTypeEnum? PlayerAvatarType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RobloxApiAvatarModelsPlayerAvatarTypeModel" /> class.
        /// </summary>
        /// <param name="playerAvatarType">The playerAvatarType [&#39;R6&#39; &#x3D; 1, &#39;R15&#39; &#x3D; 3].</param>
        public RobloxApiAvatarModelsPlayerAvatarTypeModel(PlayerAvatarTypeEnum? playerAvatarType = default(PlayerAvatarTypeEnum?))
        {
            this.PlayerAvatarType = playerAvatarType;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RobloxApiAvatarModelsPlayerAvatarTypeModel {\n");
            sb.Append("  PlayerAvatarType: ").Append(PlayerAvatarType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
