/*
 * Avatar Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Knedlex.Roblox.Avatar.ApiV1.Client.OpenAPIDateConverter;

namespace Knedlex.Roblox.Avatar.ApiV1.Model
{
    /// <summary>
    /// RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel
    /// </summary>
    [DataContract(Name = "Roblox.Api.Avatar.Models.UniverseAvatarAssetOverrideResponseModel")]
    public partial class RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel" /> class.
        /// </summary>
        /// <param name="assetID">assetID.</param>
        /// <param name="assetTypeID">assetTypeID.</param>
        /// <param name="isPlayerChoice">isPlayerChoice.</param>
        public RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel(long assetID = default(long), int assetTypeID = default(int), bool isPlayerChoice = default(bool))
        {
            this.AssetID = assetID;
            this.AssetTypeID = assetTypeID;
            this.IsPlayerChoice = isPlayerChoice;
        }

        /// <summary>
        /// Gets or Sets AssetID
        /// </summary>
        [DataMember(Name = "assetID", EmitDefaultValue = false)]
        public long AssetID { get; set; }

        /// <summary>
        /// Gets or Sets AssetTypeID
        /// </summary>
        [DataMember(Name = "assetTypeID", EmitDefaultValue = false)]
        public int AssetTypeID { get; set; }

        /// <summary>
        /// Gets or Sets IsPlayerChoice
        /// </summary>
        [DataMember(Name = "isPlayerChoice", EmitDefaultValue = true)]
        public bool IsPlayerChoice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel {\n");
            sb.Append("  AssetID: ").Append(AssetID).Append("\n");
            sb.Append("  AssetTypeID: ").Append(AssetTypeID).Append("\n");
            sb.Append("  IsPlayerChoice: ").Append(IsPlayerChoice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
